### ISSUE TITLE
Multithreading 

### ISSUE THREAD

**Issue by A-VORONKIN** [amazing-andrew/AutoHotkey.Interop#2]
Is it support Multithreading? I want check some variable with GetVar and do PixelSearch at the same time. I tried to create 2 ahk objects (`AutoHotkeyEngine ahk` for GetVar and` AutoHotkeyEngine sahk` for ExecRaw (PixelSearch) but I still can`t use them at the same time).

**Comment by amazing-andrew** [comment]
The AHKDLL will only load once using the .NET standard DLLCALL functions. For this project it means that it does not do multithreading and technically, even if you create multiple AutoHotkeyEngine it will still reference the same loaded AHKDLL.

**Comment by amazing-andrew** [comment]
I hear you can use multiple AppDomains or load the DLL multiple times manually to create mutlithreading.
