### ISSUE TITLE
Using 2 apps with AHK at the same time

### ISSUE THREAD

**Issue by A-VORONKIN** [amazing-andrew/AutoHotkey.Interop#3]
When I'm using 2 apps which are using AHK.Interop only 1 app that was launched first is working properly. In second app AHK functions are not working. How to fix it?

**Comment by amazing-andrew** [comment]
Are both of these apps running in the same process? Are they both in the same app domain?

**Comment by A-VORONKIN** [comment]
No, different process and app domain.
