### ISSUE TITLE
"To use, just include my DLL and it will deploy any files that are missing if needed." - not working

### ISSUE THREAD

**Issue by jaredbaszler** [amazing-andrew/AutoHotkey.Interop#5]
So I'm attempting to implement your DLL which sounds easy but I cannot get it to work within my own c# .NET Winforms project.  

I've downloaded your example solution and that is running just fine.  It compiles, runs and works just as you'd expect.  

I've try taking the DLL at this location: 

AutoHotkey.Interop-master\AutoHotkey.Interop-master\src\AutoHotkey.Interop\bin\Debug\AutoHotkey.Interop.dll 

and add that to my project.  It adds just fine but when I try this line:

var ahk = AutoHotkey.Interop.AutoHotkeyEngine();

I get a compilation error that is attached.  Please advise.  

![autohotkey interop error](https://cloud.githubusercontent.com/assets/9924084/14476823/b77c7314-00cf-11e6-890a-411d6d71e2f9.png)

The only differences I can see between my project and your example project is in the object browser.

Your example project looks like this:

![autohotkey interop object browser-good](https://cloud.githubusercontent.com/assets/9924084/14476966/90d72848-00d0-11e6-96e7-362d600eb5fd.png)

My project seems to be missing things:

![autohotkey interop object browser-bad](https://cloud.githubusercontent.com/assets/9924084/14476976/9e312a52-00d0-11e6-959a-11c83a206610.png)

I also went as far as adding your entire AutoHotkey.Interop proect to my project and referencing the project itself.  That also did not work.  Same compilation error.

**Comment by amazing-andrew** [comment]
it looks like you need to use a *new* operator when you are creating a new *AutoHotkeyEngine*. 

change your line from this:
`var ahk = AutoHotkey.Interop.AutoHotkeyEngine();`

to this:
`var ahk = new AutoHotkey.Interop.AutoHotkeyEngine();`

Also note that AutoHotkeyEngine is not threadsafe and that you should ever only create one AutoHotkeyEngine for your entire application, it currently does not support creating multiple instances of the engine.

**Comment by jaredbaszler** [comment]
Just call me stupid!  I respect your constraint not to with your response.  Thanks for the prompt response and making this library available.
