### ISSUE TITLE
"RegClass" Error when creating an Instance

### ISSUE THREAD

**Issue by AkilaJ** [amazing-andrew/AutoHotkey.Interop#6]
I'm creating a new AHK instance at my WPF window load event. However, if I close the window and open the same window quickly, I get a dialog box with "RegClass" as the text. This only happens if I close and open the window quickly. 

Recreation steps.
1) Create ahk = new AutoHotkey.Interop.AutoHotkeyEngine(); in the Window Load. Then call ExecRaw to execute some command.
2) Open the Window.
3) Close the Window.
4) IMPORTANT: Open the window again very quickly (within 2-3 seconds)
Outcome: There will be a dialog box with the Message "RegClass" and then the application will crash.

**Comment by AkilaJ** [comment]
Screenshot

![error](https://cloud.githubusercontent.com/assets/8046677/15094616/4fc440c4-14c7-11e6-8495-f48b9708f700.png)

**Comment by AkilaJ** [comment]
UPDATE: I've managed to find a workaround for the issue by enforcing a Singleton Instance of the AHK class. However, the issue exists for the situations where two instances of AHK with the same content are loaded. If there's a way to destruct/remove the loaded contents, it would be great. (I tried refresh and terminate without any luck)

**Comment by amazing-andrew** [comment]
The AutoHotkey Engine was never really meant to be loaded multiple times, so it should be a singleton instance. I will fix this in the library.

**Comment by AkilaJ** [comment]
Super. Thanks :)
